#!/usr/bin/env bash

# NOTE(ycho): replace `CORN_PATH` with your own.
CORN_PATH="/home/user/corn/pkm/scripts/train"

pushd ${CORN_PATH}
PYTORCH_JIT=0 python3 train_sac_arm.py +platform=debug +env=icra_base +run=icra_ours ++env.seed=56081 ++tag=policy ++global_device=cuda:0 ++path.root=/tmp/pkm/ppo-a ++icp_obs.icp.ckpt="imm-unicorn/corn-public:512-32-balanced-SAM-wd-5e-05-920" ++env.num_env=1 ++icp_obs.flat=1 ++monitor.verbose=0 ++load_ckpt=imm-unicorn/corn-public:dr-icra_base-icra_ours-ours-final-000042
popd
